### ISSUE TITLE
MuMu模拟器，无法正常开始，显示的控制台如下，请问应该如何解决？

### ISSUE THREAD

**Issue by y9918995** [MangetsuC/arkHelper#1]
[2020-07-21 09:13:57]127.0.0.1:7555
[2020-07-21 09:14:14]* daemon not running. starting it now on port 5037 *
* daemon started successfully *
connected to 127.0.0.1:7555

[2020-07-21 09:14:15]Physicalsize:1280x720

然后就不动了，模拟器打开的是活动图的界面，arkhelper.exe是用管理员权限打开的
我就是今天早上看到这个就下载下来直接运行的，请问是对安装位置有什么要求还是需要再下载个什么东西吗

**Comment by MangetsuC** [comment]
请您告知我使用的版本，如果使用的是最新版本的话，请您确认：
1. 打开了关卡，即可以看到开始行动按钮
2. 选中了战斗选项卡
我下载了最新版本的标准引擎的mumu模拟器，在同分辨率下，不修改模拟器的设置可以正常运行。如果您使用的是mumu的星云引擎也请告知我。
如果以上都没有问题，请检查arkHelper/bin/adb目录下有无arktemp.png文件

**Comment by y9918995** [comment]
现已解决，但是我也不知道是怎么解决的，把mumu模拟器、arkhelper全都重装了一遍还是不行，然后又重启了还是不行，再把arkhelper给从H盘移动到了D盘就好了。

**Comment by MangetsuC** [comment]
这可能是因为小助手在H盘没有相应的写入权限，这会导致它无法获得模拟器的屏幕信息。
实际上小助手是不需要管理员权限的，以后可以直接运行，希望小助手可以帮助您节约重复刷图的时间，以便更好地享受游戏的乐趣。

**Comment by y9918995** [comment]
对比了一下，H盘的exe文件被系统默认勾选了兼容性设置的“win7”，移动到D盘之后不知道为什么这个选项被默认不勾选了。不勾选的能正常启动。
试用了一次，能正常打关卡以及领任务，nice啊！诶嘿嘿……
请问以后可以设置自动吃理智药或者碎石吗？不过好像这个需求也不是特别刚需，一星期集中一次自己手动吃就行了。

**Comment by MangetsuC** [comment]
这个功能预计会在下一次的更新中添加，同时还会更新计划作战对特定活动关卡的支持

**Comment by MangetsuC** [comment]
我已经发布了新版本，现在可以自动使用理智合剂与碎石了
