### ISSUE TITLE
是否考虑使工具能够切换连接多开的模拟器

### ISSUE THREAD

**Issue by AutismYE** [MangetsuC/arkHelper#11]
能否在同一个模拟器多开的情况下，通过adb来切换，某个想要使用小助手的模拟器呢

**Comment by MangetsuC** [comment]
在AppData\Roaming\arkhelper\config.ini中修改相应的选项即可
一般来说是修改port选项

**Comment by MangetsuC** [comment]
已经修改了模拟器IP的处理方式，现在可以通过自定义来连接不同的多开模拟器

**Comment by AutismYE** [comment]
> 已经修改了模拟器IP的处理方式，现在可以通过自定义来连接不同的多开模拟器

谢谢你 辛苦了
