### ISSUE TITLE
希望可以增加安卓设备的支持

### ISSUE THREAD

**Issue by Tanulav** [MangetsuC/arkHelper#14]
adb已经测试过可以正常连接但是手头并没有16:9的设备，希望可以增加更多的分辨率的支持
（也可以针对不同的分辨率先上一个通用版同时调异形屏ui适配）
其次是手机设备的横屏识别不出来

**Comment by MangetsuC** [comment]
首要支持对象是模拟器，手机的话因为没有办法控制异形屏适配的宽度，我也不清楚游戏在不同宽度下是如何排布一些内容的，应该不会做。
手机设备确实始终是竖屏分辨率，我会考虑调整，但还是推荐用模拟器

**Comment by MangetsuC** [comment]
现除了基建理论已支持各类分辨率，出现的问题也在不断修正
