### ISSUE TITLE
今天开了活动，官方在资源本下边加上了一个黄色的条“资源本全开”，貌似会导致路线规划功能卡住？

### ISSUE THREAD

**Issue by y9918995** [MangetsuC/arkHelper#2]
是从主界面开始运行的路线规划，卡在资源本的界面外边，好像识别不到钱本，不停地往右拉屏幕

**Comment by MangetsuC** [comment]
我修改了res文件夹中的相关资源，现在已经可以正常使用了，请在release中下载res.7z原先的res文件夹即可

**Comment by y9918995** [comment]
太强了，MangetsuC老师
