### ISSUE TITLE
雷电模拟器无法使用，其他issue里提到的方法无法解决

### ISSUE THREAD

**Issue by dhujsi** [MangetsuC/arkHelper#21]
雷电版本4.0.59，小助手版本Vdev和release最新版
adb devices 显示emulator-5554  （状态）
点击启动控制台报错 b"adb.exe: device '127.0.0.1:5555' not found\r\n"
自定义连127.0.0.1:5554会显示计算机积极拒绝blabla
自定义连127.0.0.1:5555是* daemon started successfully 
failed to connect to 127.0.0.1:5555（此时点停止虚拟博士会卡死）
百度到的方法（重启，重装，改路径和环境变量，关相关的进程）都没法解决
issue提到的在目录打开无法解决
其他脚本的一个gui可以直接选择emulator-5554连接，不知道是什么原理……https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper
另外不开模拟器直接点开也会导致点击停止之后卡死，控制台不停刷新 no devices/emulator found
另另外，master的代码，foo\logisticDepartment目录下的Logistic.py开头小写变成大写了

**Comment by MangetsuC** [comment]
release v2.7.7已修复雷电模拟器无法使用的问题
