### ISSUE TITLE
当虚拟博士启动遇到异常时，直接停止虚拟博士将会卡死程序

### ISSUE THREAD

**Issue by AutismYE** [MangetsuC/arkHelper#26]
异常一般表现为当启动虚拟博士后，模拟器内没有任何操作进行（不影响正常使用，通常出现在我更改一些模拟器多开的设置时）。是否打算完善  **停止虚拟博士时强行终止程序所有操作**  的功能

**Comment by MangetsuC** [comment]
本项目采用多线程的方式，因此我更希望“优雅”地退出线程。在绝大多数情况下应该都能够顺利停止，后续会做出一些处理，尽量减少这种情况的出现；或进行超时处理

**Comment by MangetsuC** [comment]
v2.7.9已提供可选的强制停止
