### ISSUE TITLE
关于一些UI界面的显示

### ISSUE THREAD

**Issue by AutismYE** [MangetsuC/arkHelper#27]
当前计划使用素材模式时，选择相应的掉落物后，是否能将当前选择的掉落物显示出来，（或许可以在“选择掉落物”按钮的右边，因为目前版本的“添加”按钮的宽度似乎没有必要这么大）。

以及询问一句，在您的更新计划中，是否有打算在UI主界面中   或者添加一个按钮（点击后查看）  **查看启动虚拟博士后获得的所有掉落物**，并且随着每次关卡结束更新数据，使用文字显示就可以（像      已获得：  研磨石    10个）。

**Comment by MangetsuC** [comment]
掉落物显示后续调整。
没有在每次作战后检查掉落物的计划，这会降低效率和增大负载，但作用很小，也没有接入企鹅物流的计划

**Comment by MangetsuC** [comment]
v2.7.9已显示当前选择的掉落物
