### ISSUE TITLE
更新新主线后的计划战斗问题

### ISSUE THREAD

**Issue by lllllv** [MangetsuC/arkHelper#33]
更新了第九章之后，计划战斗不能用了，控制台输出如下日志
![图片](https://user-images.githubusercontent.com/35440760/133934665-95e64afb-61d0-4847-8501-7aeab52b9cfa.png)

是不是更新新主线后，新增的这个按钮导致逻辑出错？
![图片](https://user-images.githubusercontent.com/35440760/133934755-7f20cbe5-4aa2-4984-9942-c98eeda2e96f.png)
![图片](https://user-images.githubusercontent.com/35440760/133934970-143c4e74-082e-4462-9127-67a7fa7a48a9.png)

**Comment by MangetsuC** [comment]
是这个原因，我已经注意到了，这两天我比较忙，后续会解决的

**Comment by MangetsuC** [comment]
2.8.0修正
