### ISSUE TITLE
考虑加入一键收菜吗

### ISSUE THREAD

**Issue by 1w1w11w1** [MangetsuC/arkHelper#9]
如标题

**Comment by MangetsuC** [comment]
有在考虑，但是还未实现。
如果半成品版本大家也觉得有用的话可能会早发布不少，因此麻烦您详细描述一键基建需要的功能

**Comment by 1w1w11w1** [comment]
很期待哦。另外基建的功能目前最需要的当然是一键贸易站制造站，除此之外如自动排班，会客室收线索，开交流，送线索，还有比如说给搓玉的制造站自动补充石头的功能都很实用

**Comment by MangetsuC** [comment]
已在2.7.0实现
